### ISSUE TITLE
cant start ssbench --worker process

### ISSUE THREAD

**Issue by trentt** [swiftstack/ssbench#103]
I'm kind of new to the ssbench tool.  I have a simple topology -
storage node------------------ssbench (linux)

got this error when run the ssbench --worker 

[root@ssbench Downloads]# ssbench-worker -c 5 --zmq-host ssbench 1 &
[root@ssbench Downloads]# /usr/lib/python2.6/site-packages/ssbench/worker.py:23: DeprecationWarning: gevent.coros has been renamed to gevent.lock
  import gevent.coros
Traceback (most recent call last):
  File "/usr/bin/ssbench-worker", line 67, in <module>
    concurrency=args.concurrency, batch_size=args.batch_size)
  File "/usr/lib/python2.6/site-packages/ssbench/worker.py", line 110, in __init__
    self.work_pull.connect(work_endpoint)
  File "socket.pyx", line 475, in zmq.core.socket.Socket.connect (zmq/core/socket.c:4508)
zmq.core.error.ZMQError: Invalid argument

- Do I need ssbench-worker process up and running before i can run ssbench-master ?

**Comment by dbishop** [comment]
Not sure if this is still an issue or not, but can you try with the latest ssbench from PyPi and if it's still not working, include your "pip freeze" output?

**Comment by timuralp** [comment]
Closing this issue. Please reopen if you're still experiencing it with the latest ssbench release.
