### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by smalleni** [swiftstack/ssbench#137]
Hi, I was wondering if this project is still maintained if someone ran this on recent versions of OpenStack with Swift?

**Comment by orion** [comment]
Yes, we still maintain and use it.  Are you experiencing any particular issues?

**Comment by smalleni** [comment]
No, was just curious before trying it out! thanks, will let you know how it goes :)

**Comment by orion** [comment]
Sounds good!
