### ISSUE TITLE
pip install ssbench failed 

### ISSUE THREAD

**Issue by HugoKuo** [swiftstack/ssbench#87]
root@ss-testserver:~/bm# pip install ssbench
Downloading/unpacking ssbench
  Downloading ssbench-0.2.22.tar.gz (83Kb): 83Kb downloaded
  Running setup.py egg_info for package ssbench

    warning: no files found matching '.requirements.txt'
Requirement already satisfied (use --upgrade to upgrade): Cython in /usr/local/lib/python2.7/dist-packages (from ssbench)
Requirement already satisfied (use --upgrade to upgrade): gevent in /usr/local/lib/python2.7/dist-packages (from ssbench)
Downloading/unpacking geventhttpclient (from ssbench)
  Downloading geventhttpclient-1.0a.tar.gz (139Kb): 139Kb downloaded
  Running setup.py egg_info for package geventhttpclient

Requirement already satisfied (use --upgrade to upgrade): pyzmq==2.2.0 in /usr/local/lib/python2.7/dist-packages (from ssbench)
Downloading/unpacking gevent-zeromq (from ssbench)
  Downloading gevent_zeromq-0.2.5.tar.gz
  Running setup.py egg_info for package gevent-zeromq
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/root/bm/build/gevent-zeromq/setup.py", line 79, in <module>
        ext_modules = get_ext_modules(),
      File "/root/bm/build/gevent-zeromq/setup.py", line 36, in get_ext_modules
        return [Extension('gevent_zeromq.core', ['gevent_zeromq/core.pyx'], include_dirs=zmq.get_includes())]
      File "/usr/local/lib/python2.7/dist-packages/Cython/Distutils/extension.py", line 108, in __init__
        **kw)
    TypeError: unbound method __init__() must be called with Extension instance as first argument (got Extension instance instead)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/root/bm/build/gevent-zeromq/setup.py", line 79, in <module>

    ext_modules = get_ext_modules(),

  File "/root/bm/build/gevent-zeromq/setup.py", line 36, in get_ext_modules

    return [Extension('gevent_zeromq.core', ['gevent_zeromq/core.pyx'], include_dirs=zmq.get_includes())]

  File "/usr/local/lib/python2.7/dist-packages/Cython/Distutils/extension.py", line 108, in __init__

    **kw)

TypeError: unbound method __init__() must be called with Extension instance as first argument (got Extension instance instead)

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /root/.pip/pip.log
root@ss-testserver:~/bm#

**Comment by dbishop** [comment]
This should no longer be a problem since we got rid of the gevent_zeromq dependency.
