### ISSUE TITLE
--noop causes DivideByZero many (but not all) times

### ISSUE THREAD

**Issue by ctennis** [swiftstack/ssbench#96]
running scenarios with --noop often (but not always) generates this error:

INFO:Calculating statistics...
Traceback (most recent call last):
  File "/usr/local/bin/ssbench-master", line 597, in <module>
    args.func(args)
  File "/usr/local/bin/ssbench-master", line 256, in run_scenario
    report_scenario(args)
  File "/usr/local/bin/ssbench-master", line 304, in report_scenario
    format_numbers=format_numbers)
  File "/usr/local/lib/python2.7/site-packages/ssbench/reporter.py", line 38, in read_results
    self.stats = self.calculate_scenario_stats(nth_pctile, format_numbers)
  File "/usr/local/lib/python2.7/site-packages/ssbench/reporter.py", line 407, in calculate_scenario_stats
    self._compute_req_per_sec(size_stats)
  File "/usr/local/lib/python2.7/site-packages/ssbench/reporter.py", line 445, in _compute_req_per_sec
    stat_dict['req_count'] / delta_t,
ZeroDivisionError: float division by zero

**Comment by timuralp** [comment]
This occurs when there is only one request reported for a given worker, as all requests will have the start/end time to be the same, this results in the division by zero (1 request/0 seconds to run it). I'll change `ssbench` to print out `inf` in such cases.

**Comment by zackmdavis** [comment]
@timuralp  `N/A` or `undefined` might be more appropriate than `inf`?

**Comment by timuralp** [comment]
@zackmdavis agreed, although "inf" can be represented as a float, whereas the alternative is to configure the report to expect strings and floats for the average requests per second. I'll check how hard that is and if it's non-trivial, I think using "inf" is a reasonable compromise.

**Comment by timuralp** [comment]
Looking at the template, there is no obviously good way to handle this, unless we format the float and store it as a string prior to calling the `render_template()` method. That would be bad as the majority of numbers would be formatted in the template and one outside of it.

I'm going to fix the immediate badness by using `inf` and we can do more (lower priority) work if that is too confusing.
