### ISSUE TITLE
Using --noop with a non-existent swift cluster still hangs

### ISSUE THREAD

**Issue by portante** [swiftstack/ssbench#99]
Just running using localhost without a running swift-proxy server hangs:

```
$ bin/ssbench-master run-scenario --noop -f scenarios/small_test.scenario -S http://localhost:8080/v1/AUTH_del0/ -T ignore
```

It seems to be hanging performing some pre-authorization step ahead of the runs.

**Comment by timuralp** [comment]
The above command does hang, as it waits for for workers. However, adding the `--worker` argument, like `--worker 2` succeeds (as ssbench master hangs waiting for workers). I believe this is by intent.

Please reopen the issue if I misunderstood the problem.
